### ISSUE TITLE
大佬，请问dpt的jar包，打包是用的java什么版本，打包后的jar包会有报错，报错如下

### ISSUE THREAD

**Issue by YenKoc** [luoyesiqiu/dpt-shell#1]
DexCode offset = 12
DexCode offset = 14
fileOffset = 10686
insns item count:0,method count : 0
insns item count:24,method count : 24
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at pxb.android.axml.AxmlWriter$NodeImpl.write(AxmlWriter.java:240)
        at pxb.android.axml.AxmlWriter$NodeImpl.write(AxmlWriter.java:256)
        at pxb.android.axml.AxmlWriter.toByteArray(AxmlWriter.java:390)
        at com.wind.meditor.core.ManifestEditor.processManifest(ManifestEditor.java:74)
        at com.wind.meditor.core.FileProcesser.processManifestFile(FileProcesser.java:83)
        at com.luoye.dpt.util.ApkUtils.setExtractNativeLibs(ApkUtils.java:134)
        at com.luoye.dpt.Dpt.processApk(Dpt.java:37)
        at com.luoye.dpt.Dpt.main(Dpt.java:16)

**Comment by luoyesiqiu** [comment]
这个项目打包用的Java8。不过感觉和Java版本没关系，仓库里打好的包能用吗？

**Comment by YenKoc** [comment]
> 这个项目打包用的Java8。不过感觉和Java版本没关系，仓库里打好的包能用吗？

打包好的项目可以用，ac版本就会出问题，然后win下release的很稳，其实我是打算用来ctf比赛出题的，所以想把包名抹了，然后加自己的东西，怕被选手搜到这个项目哈哈哈，大佬微信有联系方式吗，我跟您详聊下

**Comment by luoyesiqiu** [comment]
im_zzZZ
