### ISSUE TITLE
Android8.0打开闪退

### ISSUE THREAD

**Issue by YsielX** [luoyesiqiu/dpt-shell#13]
使用avd虚拟机和Android8真机都会闪退，报错如下
```
Process: com.example.testchouqu, PID: 1668
java.lang.RuntimeException: Unable to instantiate application com.luoyesiqiu.shell.ProxyApplication: java.lang.ClassNotFoundException: Didn't find class "com.luoyesiqiu.shell.ProxyApplication" on path: DexPathList[[zip file "/data/app/com.example.testchouqu-anuw1TT7ruMqFk3nnLJhbg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.testchouqu-anuw1TT7ruMqFk3nnLJhbg==/lib/arm64, /data/app/com.example.testchouqu-anuw1TT7ruMqFk3nnLJhbg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64, /preas/lib64]]
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1059)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6590)
	at android.app.ActivityThread.-wrap2(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.luoyesiqiu.shell.ProxyApplication" on path: DexPathList[[zip file "/data/app/com.example.testchouqu-anuw1TT7ruMqFk3nnLJhbg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.testchouqu-anuw1TT7ruMqFk3nnLJhbg==/lib/arm64, /data/app/com.example.testchouqu-anuw1TT7ruMqFk3nnLJhbg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64, /preas/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1089)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1053)
	... 9 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.example.testchouqu-anuw1TT7ruMqFk3nnLJhbg==/base.apk because: Unrecognized version number in /data/app/com.example.testchouqu-anuw1TT7ruMqFk3nnLJhbg==/base.apk: 0 3 9 
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
		at dalvik.system.DexFile.<init>(DexFile.java:100)
		at dalvik.system.DexFile.<init>(DexFile.java:74)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:75)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:38)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:719)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:752)
		at android.app.LoadedApk.getResources(LoadedApk.java:1005)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2505)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6497)
		... 8 more
Force finishing activity com.example.testchouqu/com.example.nothingcode.MainActivity
```
还望作者解决或者指点一下！

**Comment by luoyesiqiu** [comment]
是不是二次加固了

**Comment by YsielX** [comment]
> 

并不是，我直接使用该工具加固了一次，放入Android8手机就会闪退

**Comment by luoyesiqiu** [comment]
apk方便发吗

**Comment by YsielX** [comment]
[executable.zip](https://github.com/luoyesiqiu/dpt-shell/files/9481937/executable.zip)
加壳前和加壳后
