### ISSUE TITLE
unable to do

### ISSUE THREAD

**Issue by allowdoc** [luoyesiqiu/dpt-shell#31]
C:\Users\pc\Downloads\Compressed\executable\executable>java -jar dpt.jar -f ready.apk
2023-11-08 06:14:12.298 [main]  dpt-processor   Apk main process path: C:\Users\Endless\AppData\Local\Temp\dptOut
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at pxb.android.StringItems.read(StringItems.java:45)
        at pxb.android.axml.AxmlParser.next(AxmlParser.java:245)
        at com.luoye.dpt.util.ManifestUtils.getValue(ManifestUtils.java:60)
        at com.luoye.dpt.util.ManifestUtils.getPackageName(ManifestUtils.java:91)
        at com.luoye.dpt.Dpt.processApk(Dpt.java:77)
        at com.luoye.dpt.Dpt.main(Dpt.java:21)

**Comment by luoyesiqiu** [comment]
What you jdk version？

**Comment by allowdoc** [comment]
Latest just installed fresh

**Comment by vipeweb** [comment]
same problem

2024-02-01 20:56:10.852 [main]  dpt-processor   Apk main process path: C:\Users\filip\AppData\Local\Temp\dptOut
2024-02-01 20:56:10.854 [main]  dpt-processor   writeZipEntry err = java.io.FileNotFoundException: C:\Users\filip\AppData\Local\Temp\dptOut (Acesso negado)
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at pxb.android.StringItems.read(StringItems.java:45)
        at pxb.android.axml.AxmlParser.next(AxmlParser.java:245)
        at com.luoye.dpt.util.ManifestUtils.getValue(ManifestUtils.java:60)
        at com.luoye.dpt.util.ManifestUtils.getPackageName(ManifestUtils.java:91)
        at com.luoye.dpt.buildler.Apk.process(Apk.java:115)
        at com.luoye.dpt.buildler.Apk.protect(Apk.java:147)
        at com.luoye.dpt.Dpt.main(Dpt.java:19)
