### ISSUE TITLE
大佬看下这个报错是什么问题

### ISSUE THREAD

**Issue by ReverseFeng** [luoyesiqiu/dpt-shell#33]
大佬看下这个报错是什么问题

FATAL EXCEPTION: main
                                                                                                    Process: com.luoye.dpt, PID: 28579
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for void com.luoyesiqiu.shell.JniBridge.ia(android.content.Context) (tried Java_com_luoyesiqiu_shell_JniBridge_ia and Java_com_luoyesiqiu_shell_JniBridge_ia__Landroid_content_Context_2)
                                                                                                    	at com.luoyesiqiu.shell.JniBridge.ia(Native Method)
                                                                                                    	at com.luoyesiqiu.shell.ProxyComponentFactory.instantiateClassLoader(ProxyComponentFactory.java:132)
                                                                                                    	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:946)
                                                                                                    	at android.app.LoadedApk.getClassLoader(LoadedApk.java:982)
                                                                                                    	at android.app.LoadedApk.getResources(LoadedApk.java:1214)
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:2655)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7013)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:260)

**Comment by luoyesiqiu** [comment]
现在用的什么版本的

**Comment by ReverseFeng** [comment]
github上最新的 在as中自己编译  跑出来就是这个报错

**Comment by luoyesiqiu** [comment]
可能和混淆有关，把混淆关了试试

**Comment by luoyesiqiu** [comment]
或者试试使用debug构建：gradlew shell:assembleDebug

**Comment by ReverseFeng** [comment]
大佬 看看这个报错  编译时候触发的    找不见这个shell   A problem occurred configuring project ':shell'.
> Failed to notify project evaluation listener.
   > java.lang.NullPointerException (no error message)
   > Task with name 'assembleRelease' not found in project ':shell'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 151ms

**Comment by luoyesiqiu** [comment]
gradlew shell:assemble可以吗

**Comment by ReverseFeng** [comment]
不行呀 一直说这个shell找不见

**Comment by ReverseFeng** [comment]
大佬 看下这个报错  java.lang.ClassNotFoundException: com.android.webview.chromium.WebViewChromiumFactoryProviderForOMR1
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:453)
                                                                                                    	at android.webkit.WebViewFactory.getWebViewProviderClass(WebViewFactory.java:138)
                                                                                                    	at android.webkit.WebViewFactory.getProviderClass_nubia(WebViewFactory.java:218)
                                                                                                    	at android.webkit.WebViewFactory.getProvider_nubia(WebViewFactory.java:335)
                                                                                                    	at android.app.ActivityThread$2.run(ActivityThread.java:5915)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.webview.chromium.WebViewChromiumFactoryProviderForOMR1" on path: DexPathList[[zip file "/system/app/webview/webview.apk"],nativeLibraryDirectories=[/system/app/webview/lib/arm64, /system/app/webview/webview.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at java.lang.Class.classForName(Native Method) 
                                                                                                    	at java.lang.Class.forName(Class.java:453) 
                                                                                                    	at android.webkit.WebViewFactory.getWebViewProviderClass(WebViewFactory.java:138) 
                                                                                                    	at android.webkit.WebViewFactory.getProviderClass_nubia(WebViewFactory.java:218) 
                                                                                                    	at android.webkit.WebViewFactory.getProvider_nubia(WebViewFactory.java:335) 
                                                                                                    	at android.app.ActivityThread$2.run(ActivityThread.java:5915) 
                                                                                                    	Suppressed: java.io.IOException: No original dex files found for dex location /system/app/webview/webview.apk
                                                                                                    		at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                                    		at dalvik.system.DexFile.openDexFile(DexFile.java:505)
                                                                                                    		at dalvik.system.DexFile.<init>(DexFile.java:105)
                                                                                                    		at dalvik.system.DexFile.<init>(DexFile.java:79)
                                                                                                    		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:382)
                                                                                                    		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
                                                                                                    		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
                                                                                                    		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
                                                                                                    		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                                                                                                    		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
                                                                                                    		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
                                                                                                    		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
                                                                                                    		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
                                                                                                    		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:701)
                                                                                                    		at android.app.LoadedApk.getClassLoader(LoadedApk.java:735)
                                                                                                    		at android.app.ContextImpl.getClassLoader(ContextImpl.java:304)
                                                                                                    		at android.webkit.WebViewFactory.getProviderClass_nubia(WebViewFactory.java:210)

**Comment by luoyesiqiu** [comment]
webview.apk有dex文件吗

**Comment by ReverseFeng** [comment]
app本身没有这个webview.apk  这个webview.apk是系统的

**Comment by luoyesiqiu** [comment]
不管是系统的还是哪里的，如果这个webview.apk里面有没有dex文件的话可能加载不到

**Comment by ReverseFeng** [comment]
不加壳之前可以正常运行，加壳之后就报错这个了，是添加DEx  pathlist的遇到的问题？这个有办法解决吗，需要的话我给你例子

**Comment by luoyesiqiu** [comment]
提供apk我看下

**Comment by ReverseFeng** [comment]
链接：https://pan.baidu.com/s/1yloH_7N0FiNkSwiVIUPcaw 
提取码：0seq 
--来自百度网盘超级会员V6的分享   大佬你看下 我这是安卓8崩溃  java.lang.ClassNotFoundException: Didn't find class "com.android.webview.chromium.WebViewChromiumFactoryProviderForOMR1" on path

**Comment by ReverseFeng** [comment]
佬，能留个联系方式吗？

**Comment by luoyesiqiu** [comment]
https://t.me/+cLsGN5qXp3hkMDI1

**Comment by luoyesiqiu** [comment]
或者vx:dnhpZF9pbXpoYW8=
