### ISSUE TITLE
不支持androidx吗

### ISSUE THREAD

**Issue by helengray** [luoyesiqiu/dpt-shell#39]
java.lang.NoSuchFieldError: No field b of type Landroid/content/Context; in class La/a; or its superclasses (declaration of 'a.a' appears in /data/app/com.yealink.astro.demo-b65DoihcpKR4spxJzVtMhA==/base.apk)
                                                                                                    	at androidx.activity.ComponentActivity.l(SourceFile:3)
                                                                                                    	at androidx.activity.ComponentActivity.<init>(SourceFile:104)
                                                                                                    	at androidx.fragment.app.j.<init>(SourceFile:1)
                                                                                                    	at d.g.<init>(SourceFile:1)
                                                                                                    	at com.yealink.astro.demo.MainActivity.<init>(Unknown Source:0)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
                                                                                                    	at com.luoyesiqiu.shell.ProxyComponentFactory.instantiateActivity(Unknown Source:81)
                                                                                                    	at android.app.Instrumentation.newActivity(Instrumentation.java:1264)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3798)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4074)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8347)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by luoyesiqiu** [comment]
跟androidX应该没关系

**Comment by helengray** [comment]
[app-release.zip](https://github.com/luoyesiqiu/dpt-shell/files/15084557/app-release.zip)
这个是demo app，你看下你那边能不能复现

**Comment by luoyesiqiu** [comment]
晚点试试
