### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by helengray** [luoyesiqiu/dpt-shell#46]
项目是Androidx的，加固后抛异常
`java.lang.IncompatibleClassChangeError: Class androidx.activity.ComponentActivity implements non-interface class b.a (declaration of 'androidx.activity.ComponentActivity' appears in /data/user/0/<package_name>/code_cache/i11111i111.zip)`

**Comment by helengray** [comment]
完整堆栈

`
java.lang.IncompatibleClassChangeError: Class androidx.activity.ComponentActivity implements non-interface class b.a (declaration of 'androidx.activity.ComponentActivity' appears in /data/user/0/<package_name>/code_cache/i11111i111.zip)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at wc.b.a(SourceFile:11)
                                                                                                    	at <package_name>.ComApplication.onCreate(SourceFile:125)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7336)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2382)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:223)
                                                                                                    	at android.os.Looper.loop(Looper.java:324)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8558)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
`

**Comment by luoyesiqiu** [comment]
必现吗？看堆栈怎么没有ProxyApplication

**Comment by helengray** [comment]
必现，应该是已经在执行目标Application了

**Comment by blackandwhiteforzj** [comment]
可以发一下加固前的apk

**Comment by blackandwhiteforzj** [comment]
> 必现，应该是已经在执行目标Application了

加固前的apk发一下

**Comment by helengray** [comment]
> > 必现，应该是已经在执行目标Application了
> 
> 加固前的apk发一下

[app-release.zip](https://github.com/user-attachments/files/15955556/app-release.zip)

**Comment by luoyesiqiu** [comment]
这边试了一下，是可以起来的
