### ISSUE TITLE
你好，大佬帮忙看下这种错误是因为什么呢？是哪里出问题了

### ISSUE THREAD

**Issue by wenbo-ya** [luoyesiqiu/dpt-shell#65]
2024-10-28 18:11:27.908	[main]	dpt-processor	Apk main process path: C:\Windows\TEMP\dptOut
2024-10-28 18:11:33.802	[main]	dpt-processor	DexCode offset = 12
2024-10-28 18:11:33.802	[main]	dpt-processor	DexCode offset = 3134
2024-10-28 18:11:33.804	[main]	dpt-processor	fileOffset = 2331382
java.io.FileNotFoundException: C:\Windows\TEMP\dptOut\assets\OoooooOooo (????????????·????)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:346)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:260)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:215)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
	at com.luoye.dpt.util.MultiDexCodeUtils.writeMultiDexCode(MultiDexCodeUtils.java:80)
	at com.luoye.dpt.builder.Apk.extractDexCode(Apk.java:456)
	at com.luoye.dpt.builder.Apk.process(Apk.java:120)
	at com.luoye.dpt.builder.Apk.protect(Apk.java:149)
	at com.luoye.dpt.Dpt.main(Dpt.java:19)

**Comment by wenbo-ya** [comment]
这边验证了下，这种情况是同时命令加固两个包会出现，有办法解决吗

**Comment by luoyesiqiu** [comment]
同时加固两个包？怎么写的命令

**Comment by wenbo-ya** [comment]
![image](https://github.com/user-attachments/assets/02084477-17b3-493a-a10d-ac6303931fc2)
打开了两个窗口，基本同时触发命令

**Comment by wenbo-ya** [comment]
命令是 java -jar dpt.jar -x -f E:\executable\apk

**Comment by luoyesiqiu** [comment]
工作目录的内容一直有变更的，同时跑起来会资源不同步导致报错

**Comment by wenbo-ya** [comment]
针对这个同时跑的情况，有办法解决吗

**Comment by wenbo-ya** [comment]
需要我这边做调整吗

**Comment by wenbo-ya** [comment]
已经解决，感谢回复
