### ISSUE TITLE
Not WORK !!!!!!!

### ISSUE THREAD

**Issue by dfdfdfs** [luoyesiqiu/dpt-shell#7]
DexCode offset = 56
DexCode offset = 314494
DexCode offset = 317510
DexCode offset = 330384
DexCode offset = 330780
DexCode offset = 767346
DexCode offset = 775124
DexCode offset = 781042
DexCode offset = 782714
DexCode offset = 797392
DexCode offset = 801308
DexCode offset = 802902
DexCode offset = 803164
fileOffset = 803562
insns item count:5632,method count : 5632
insns item count:89,method count : 89
insns item count:42,method count : 42
insns item count:13,method count : 13
insns item count:8481,method count : 8481
insns item count:105,method count : 105
insns item count:33,method count : 33
insns item count:51,method count : 51
insns item count:158,method count : 158
insns item count:58,method count : 58
insns item count:42,method count : 42
insns item count:9,method count : 9
insns item count:5,method count : 5
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module j
        at pxb.android.axml.AxmlWriter$NodeImpl.write(AxmlWriter.java:240)
        at pxb.android.axml.AxmlWriter$NodeImpl.write(AxmlWriter.java:256)
        at pxb.android.axml.AxmlWriter.toByteArray(AxmlWriter.java:390)
        at com.wind.meditor.core.ManifestEditor.processManifest(ManifestEditor.java:74)
        at com.wind.meditor.core.FileProcesser.processManifestFile(FileProcesser.java:83)
        at com.luoye.dpt.util.ApkUtils.setExtractNativeLibs(ApkUtils.java:137)
        at com.luoye.dpt.Dpt.processApk(Dpt.java:71)
        at com.luoye.dpt.Dpt.main(Dpt.java:21)

**Comment by dfdfdfs** [comment]
???

**Comment by luoyesiqiu** [comment]
抱歉，之前看到但是不知道怎么回。可以提供一下apk吗
