### ISSUE TITLE
报错了，需要更新apktool 版本

### ISSUE THREAD

**Issue by cgapk123** [luoyesiqiu/dpt-shell#79]
com.android.dex.DexException: Unexpected magic: [0x64, 0x65, 0x78, 0x0a, 0x30, 0x34, 0x30, 0x00]
        at com.android.dex.TableOfContents.readHeader(TableOfContents.java:86)
        at com.android.dex.TableOfContents.readFrom(TableOfContents.java:72)
        at com.android.dex.Dex.<init>(Dex.java:81)
        at com.android.dex.Dex.<init>(Dex.java:75)
        at com.luoye.dpt.util.DexUtils.writeHashes(DexUtils.java:240)
        at com.luoye.dpt.builder.Apk.lambda$extractDexCode$0(Apk.java:437)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2024-12-24 12:12:12.396 [main]  dpt-processor   DexCode offset = 8
2024-12-24 12:12:12.397 [main]  dpt-processor   fileOffset = 10
2024-12-24 12:12:12.401 [main]  dpt-processor   insns item count:0,method count : 0
2024-12-24 12:12:12.578 [main]  dpt-processor   zipDataLen: 1531
2024-12-24 12:12:12.579 [main]  dpt-processor   unShellDexLen:10908

上面是反编译APK报错的，然后我使用其他电脑工具去反编译APK也报错，最后查询更新至最新版 apktool_2.10.0.jar 后正常了，但这个项目的还是不行，所以这个项目的也应该需要更新apktool这种

**Comment by luoyesiqiu** [comment]
应该是不支持新版的dex
