### ISSUE TITLE
一打开就闪退

### ISSUE THREAD

**Issue by Uggpic** [luoyesiqiu/dpt-shell#82]
java.lang.NoSuchMethodError: No direct method <init>(Lb/b;Lb/c;)V in class Lb/a; or its super classes (declaration of 'b.a' appears in /data/app/ru.zdevs.zarchiver-94me3GTMHEn_D31Bt13sKg==/base.apk)
	at b.b.<init>(SourceFile:15)
	at b.d.k(SourceFile:30)
	at c.c.b(SourceFile:10)
	at c.c.a(SourceFile:547)
	at c.d.u(SourceFile:5)
	at c.d.s(SourceFile:191)
	at android.support.constraint.ConstraintLayout.onMeasure(SourceFile:168)
	at android.view.View.measure(View.java:23454)
	at android.widget.Toolbar.measureChildCollapseMargins(Toolbar.java:1549)
	at android.widget.Toolbar.onMeasure(Toolbar.java:1652)
	at android.view.View.measure(View.java:23454)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.widget.ActionBarContainer.onMeasure(ActionBarContainer.java:298)
	at android.view.View.measure(View.java:23454)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
	at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:506)
	at android.view.View.measure(View.java:23454)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
	at android.view.View.measure(View.java:23454)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:893)
	at android.view.Choreographer.doFrame(Choreographer.java:812)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by luoyesiqiu** [comment]
哪个版本呀？

**Comment by luoyesiqiu** [comment]
应该修复了

**Comment by luoyesiqiu** [comment]
> @luoyesiqiu 好像对某些安装包不稳定，出现各种问题 [app.zip](https://github.com/user-attachments/files/18306917/app.zip) ![Screenshot_202](https://private-user-images.githubusercontent.com/175627399/400141098-f5570bfa-869d-4545-b1a5-d0d785efc9ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNDQ5NjcsIm5iZiI6MTczNjA0NDY2NywicGF0aCI6Ii8xNzU2MjczOTkvNDAwMTQxMDk4LWY1NTcwYmZhLTg2OWQtNDU0NS1iMWE1LWQwZDc4NWVmYzljYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNVQwMjM3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2ZhNmNkNTZiZjk5ZDkwZjM5MmZhYTMyZDk2NWUxOTcxNTU3NGM5MTcyMGZkYjU3MDJhNjJhMjM0ODQ1MzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9Nl01rG8Ng_PNkfK81K-SHc-N3D2O4yP6O9cGFc_Ii8)

已修复。下次不同的问题请提一个新的issue
